version: "1.0"
info:
  model: int-scaffold
packages:
- name: MoaaGitNew_11Project
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
services:
- serviceName: project.moaagitnew_11.integrations:edgeFlow
  packages:
  - name: MoaaGitNew_11Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1957
